# Generated by Django 4.2.1 on 2023-05-25 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_rename_done_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="done",
        ),
    ]
